/**
 * This file was automatically generated by the Mule Development Kit
 */
package org.mule.modules.drupal8;

import org.junit.Rule;
import org.junit.Test;
import org.mule.construct.Flow;
import org.mule.tck.junit4.FunctionalTestCase;
import org.mule.tck.junit4.rule.DynamicPort;

public class Drupal8ConnectorNamespaceTest extends FunctionalTestCase
{
    @Rule
    public DynamicPort drupalPort = new DynamicPort("drupal.port");

    @Override
    protected String getConfigResources()
    {
        return "mule-config.xml";
    }

    @Test
    public void testFlow() throws Exception
    {
    }

    /**
     * Retrieve a flow by name from the registry
     * 
     * @param name
     *            Name of the flow to retrieve
     */
    protected Flow lookupFlowConstruct(String name)
    {
        return (Flow) FunctionalTestCase.muleContext.getRegistry().lookupFlowConstruct(name);
    }
}
